<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Version>0.1.0</Version>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
    <_SkipUpgradeNetAnalyzersNuGetWarning>true</_SkipUpgradeNetAnalyzersNuGetWarning>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.BuildServices" Version="11.3.2" ExcludeAssets="all" PrivateAssets="all" />
    <PackageReference Include="Avalonia.Win32" Version="11.3.12" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Headless" Version="11.3.12" PrivateAssets="all" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <ProjectReference Include="../HumCapture.Coordinator.Repository/HumCapture.Coordinator.Repository.csproj" />
  </ItemGroup>
</Project>
