import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { encodeCaptureArtifact } from "../src/capture-artifact-conformance.js";
import { sha256 } from "../src/timing-contract-conformance.js";

export function scientificVectors() {
  const protocol = JSON.parse(readFileSync(new URL("./control/valid/fixed-session-lifecycle.json", import.meta.url))).protocol_snapshot;
  protocol.schema_version = "1.1.0";
  protocol.scientific_rules = [
    { rule_id: "CADENCE.MIN", role_id: protocol.source_roles[0].role_id, level: "REQUIRED", metric: "OBSERVED_MILLIHZ", operator: "GE", threshold: 29000 },
    { rule_id: "IMAGE.WIDTH", role_id: protocol.source_roles[0].role_id, level: "REQUIRED", metric: "DECODED_WIDTH", operator: "EQ", threshold: 1920 }
  ];
  delete protocol.snapshot_content_sha256;
  protocol.snapshot_content_sha256 = sha256(encodeCaptureArtifact(protocol));
  // Expected values are explicit, not generated by the implementation under test.
  const cases = [
    [[], "REVIEW_REQUIRED"],
    [[{ level: "REQUIRED", outcome: "PASS" }], "CONFORMANT"],
    [[{ level: "REQUIRED", outcome: "FAIL" }], "REJECTED"],
    [[{ level: "REQUIRED", outcome: "NOT_ASSESSED" }], "REVIEW_REQUIRED"],
    [[{ level: "PREFERRED", outcome: "FAIL" }], "DEGRADED_ACCEPTABLE"],
    [[{ level: "PREFERRED", outcome: "NOT_ASSESSED" }], "DEGRADED_ACCEPTABLE"],
    [[{ level: "INFORMATIONAL", outcome: "PASS" }], "REVIEW_REQUIRED"],
    [[{ level: "REQUIRED", outcome: "PASS" }, { level: "INFORMATIONAL", outcome: "FAIL" }], "CONFORMANT"],
    [[{ level: "REQUIRED", outcome: "NOT_ASSESSED" }, { level: "REQUIRED", outcome: "FAIL" }], "REJECTED"],
    [[{ level: "REQUIRED", outcome: "NOT_ASSESSED" }, { level: "PREFERRED", outcome: "FAIL" }], "REVIEW_REQUIRED"]
  ].map(([conditions, expected]) => ({ conditions, expected }));
  return { evidence: "Synthetic protocol and rule cases; thresholds are fixtures, not product defaults", protocol, cases };
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv[2] !== "--write") throw new Error("Use --write to regenerate fixtures.");
  writeFileSync(new URL("./timing/v1/scientific-rules-vectors.json", import.meta.url), JSON.stringify(scientificVectors(), null, 2) + "\n");
}
